packages:
  - 'apps/*'
  - 'examples/*'
  - 'packages/*'

shamefullyHoist: true

allowBuilds:
  better-sqlite3: true

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  # Nuxt
  - '@nuxt/*'
  - '@nuxtjs/*'
  - 'nuxt'
  - 'nuxt-*'
  # Vercel
  - '@vercel/*'
  - '@ai-sdk/*'
  - 'ai'
