packages:
  - 'apps/*'
  - 'examples/*'
  - 'packages/*'

shamefullyHoist: true

allowBuilds:
  '@nestjs/core': false
  '@parcel/watcher': false
  '@swc/core': false
  better-sqlite3: true
  cbor-extract: false
  esbuild: false
  maplibre-gl: false
  sharp: false
  unrs-resolver: false
  vue-demi: false

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  # Nuxt
  - '@nuxt/*'
  - '@nuxtjs/*'
  - 'nuxt'
  - 'nuxt-*'
  # Vercel
  - '@vercel/*'
  - '@ai-sdk/*'
  - 'ai'
  - 'eve'
  - 'create-eve'

overrides:
  '@ai-sdk/vue>ai': 7.0.70
  '@ai-sdk/workflow>ai': 7.0.70
  'undici@5': 6.28.0

